version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  notify:
    steps:
      webhooks:
        - url: http://14.232.215.113:9164/api/webhook/circleci?token= 2f528a7cd9a765f59ff11133782ea8527eb0e7f9        
orbs:
  slack: circleci/slack@x.y.z
workflows:
  test-workflow:
    jobs:
      - build
      - notify
