version: 2.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  notify:
     docker:
        - image: circleci/ruby:2.4.1
     description: Send webhook to slackbot about job status
     steps:
      - run:
          name: On success
          when: on_success
          command: |
            curl 'http://14.232.215.113:9164/api/webhook/circleci?token=2f528a7cd9a765f59ff11133782ea8527eb0e7f9'  -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_parameters":{"CIRCLE_JOB":"'"$CIRCLE_JOB"'"},"outcome":"fixed","build_url":"'"$CIRCLE_BUILD_URL"'"}}' -H "Content-Type: application/json" -X POST -i
      - run:
          name: On fail
          when: on_fail
          command: |
            curl 'http://14.232.215.113:9164/api/webhook/circleci?token=2f528a7cd9a765f59ff11133782ea8527eb0e7f9' -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_parameters":{"CIRCLE_JOB":"'"$CIRCLE_JOB"'"},"outcome":"failed","build_url":"'"$CIRCLE_BUILD_URL"'"}}' -H "Content-Type: application/json" -X POST -i       
workflows:
  version: 2
  test-workflow:
    jobs:
      - build
      - notify:
         requires:
           - build

